# Generated by Django 3.1.4 on 2020-12-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_fee_hostel_room_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostel',
            name='no_of_students',
        ),
        migrations.AlterField(
            model_name='hostel',
            name='no_of_rooms',
            field=models.IntegerField(default=25),
        ),
    ]
