# Generated by Django 3.1.4 on 2020-12-09 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20201208_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='r_hostelno',
        ),
        migrations.RemoveField(
            model_name='student',
            name='s_hostelno',
        ),
        migrations.RemoveField(
            model_name='student',
            name='s_roomno',
        ),
        migrations.DeleteModel(
            name='Fee',
        ),
        migrations.DeleteModel(
            name='Hostel',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
