# Generated by Django 3.1.4 on 2020-12-09 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20201209_0905'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel_no', models.IntegerField()),
                ('room_no', models.IntegerField()),
                ('room_capacity', models.IntegerField()),
                ('s_id', models.IntegerField()),
                ('s_name', models.CharField(max_length=70)),
                ('s_fathername', models.CharField(max_length=70)),
                ('s_department', models.CharField(max_length=70)),
                ('fee_sem', models.IntegerField()),
                ('fee_status', models.CharField(max_length=10)),
            ],
        ),
    ]
