# Generated by Django 3.1.4 on 2020-12-09 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='s_id',
            field=models.CharField(max_length=12),
        ),
    ]
